---
apiVersion: v1
kind: Service
metadata:
  name: couchdb-svc
spec:
  type: NodePort
  selector:
    app: couchdb
  externalIPs:
    - 129.114.27.100
  ports:
    - name: couchdb-port
      protocol: TCP
      port: 5984
      targetPort: 5984
      nodePort: 30002
...
