---
apiVersion: v1
kind: Service
metadata:
  name: kafka-svc-worker
spec:
  type: NodePort
  selector:
    app: kafka-worker
  externalIPs:
    - 129.114.27.100
  ports:
    - name: kafka-port
      protocol: TCP
      port: 9092
      targetPort: 9092
      nodePort: 30001
...
