---
- name: "Install Le Docker"
  hosts: #Need Host
  remote_user: cc
  gather_facts: no
  become: yes

  tasks:
  - name: "Apt Update"
    apt:
      name: aptitude
      state: latest
      update_cache: yes
      force_apt_get: yes

  - name: "Installing Apt Packages"
    apt:
      name: "{{ item }}"
      state: latest
    loop: [ 'apt-transport-https', 'ca-certificates', 'curl', 'software-properties-common', 'python3-pip', 'virtualenv', 'python3-setuptools']

  - name: "Add Docker key"
    apt_key:
      url: https://download.docker.com/linux/ubuntu/gpg
      state: present

  - name: "Add Docker Repo"
    apt_repository:
      repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable
      state: present

  - name: "Install Docker"
    apt:
      update_cache: yes
      name: docker-ce
      state: latest

  - name: "Install Docker Pip"
    pip:
      name: docker

  # This will probably need to change to something else in the future.
  - name: "Pull Docker Img"
    docker_image:
      name: nginx
      source: pull

  - name: "Start Docker"
    docker_container:
      name: Quibb_Docker
      image: nginx
      state: started
...
