---
- name: Update advertised listener
  ansible.builtin.lineinfile:
    path: ~/kafka/kafka_2.13-2.6.2/config/server.properties
    regexp: '^#advertised.listeners=PLAINTEXT://your.host.name:9092'
    line: advertised.listeners=PLAINTEXT://129.114.25.169:9092

- name: Start Zookeeper Service
  ansible.builtin.service:
    name: zookeeper
    enabled: yes
    state: started
  become: yes

- name: Start Kafka Service
  ansible.builtin.service:
    name: kafka
    enabled: yes
    state: started
  become: yes
...
