apiVersion: batch/v1
kind: Job
metadata:
  name: spark-driver-job  # This will run the Spark driver
spec:
  template:
    metadata:
      labels:
        app: sparkDriverApp
    spec:
      hostname: spark-driver-host
      nodeSelector:
        kubernetes.io/hostname: kubernetes-main
      containers:
        - name: spark-driver

          image: 129.114.27.100:5000/my-spark:latest
          imagePullPolicy: Always
          env:
            - name: SPARK_LOCAL_IP
              value: "spark-driver-host"
            - name: SPARK_HOME
              value: "/spark-3.2.0-bin-hadoop3.2-scala2.13"

          ports:
            - containerPort: 4040
            - containerPort: 7076
            - containerPort: 7079

          command: ["/run_iters.sh"]
      restartPolicy: Never
...