---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: spark-worker-deploy
spec:
  replicas: 5 
  selector:
    matchLabels:
      app: sparkWorkerApp
  minReadySeconds: 5

  template:
    metadata:
      labels:
        app: sparkWorkerApp
    spec:
      hostname: spark-worker-host  # we need it to set the SPARK_LOCAL_IP
      containers:
        - name: spark-worker
          image: 129.114.27.100:5000/my-spark:latest
          ports:
            - containerPort: 7078
            - containerPort: 7079
            - containerPort: 8081
          env:
            - name: SPARK_LOCAL_IP
              value: "spark-worker-host"
            - name: SPARK_NO_DAEMONIZE
              value: "1"
            - name: SPARK_HOME
              value: "/spark-3.2.0-bin-hadoop3.2-scala2.13"
          imagePullPolicy: Always  # This forces the node to pull the image
          command: ["$(SPARK_HOME)/sbin/start-worker.sh"]
          args: ["spark://spark-master-svc:7077", "--properties-file", "$(SPARK_HOME)/conf/spark-worker.conf"]
...