---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-main
spec:
  selector:
    matchLabels:
      app: kafka-main
  minReadySeconds: 5

  template:
    metadata:
      labels:
        app: kafka-main
    spec:
      nodeSelector:
        kubernetes.io/hostname: kubernetes-main
      containers:
      - name: kafka-main
        image: wurstmeister/kafka
        ports:
        - containerPort: 9092
        env:
        - name: KAFKA_BROKER_ID
          value: "0"
        - name: KAFKA_ADVERTISED_PORT
          value: "30000"
        - name: KAFKA_ADVERTISED_HOST_NAME
          value: 129.114.27.100
        - name: KAFKA_ZOOKEEPER_CONNECT
          value: zookeeper-svc:2181
        - name: KAFKA_CREATE_TOPICS
          value: "MeetUpNewYork:1:1,MeetUpSeattle:1:1"