---
apiVersion: v1
kind: Service
metadata:
  name: kafka-svc-main
spec:
  type: NodePort
  selector:
    app: kafka-main
  externalIPs:
    - 129.114.27.100
  ports:
    - name: kafka-port
      protocol: TCP
      port: 9092
      targetPort: 9092
      nodePort: 30000
...
