apiVersion: batch/v1
kind: Job
metadata:
  name: consumer-job
spec:
  template:
    metadata:
      labels:
        app: consumer
    spec:
      hostname: consumer-host
      nodeSelector:
        kubernetes.io/hostname: kubernetes-main
      containers:
      - name: consumer
        image: 129.114.27.100:5000/consumer
        imagePullPolicy: Always
        command: ["python3"]
        args: ["/consumer.py"]
      restartPolicy: Never