---
  - name: Default deny Incoming
    community.general.ufw:
      default: deny
      direction: incoming
    become: true

  - name: Default Allow Outbound
    community.general.ufw:
      default: allow
      direction: outgoing
    become: true

  - name: Allow SSH
    community.general.ufw:
      rule: limit
      port: ssh
      proto: tcp
    become: true

  - name: Allow Zookeeper
    community.general.ufw:
      rule: limit
      port: 2181
      proto: tcp
    become: true

  - name: Allow Kafka
    community.general.ufw:
      rule: limit
      port: 9092
      proto: tcp
    become: true

  - name: Enable State
    community.general.ufw:
      state: enabled
    become: true
...
