---
- name: Using the new Openstack Cloud collection
  hosts: MyLocalVMs  # remember, the requestor is the local machine
  collections:
    - openstack.cloud

  tasks:

  - name: Obtain info about our Chameleon cloud identity domain
    openstack.cloud.identity_domain_info:
        cloud: CH-822922   # this is the nickname from our clouds.yaml file
    register: result

  - name: "Print results"
    debug:
        msg: "{{ result.openstack_servers }}"
... 

