---
- hosts: MyChameleonVMs
  remote_user: cc
  collections:
    - openstack.cloud

  tasks:
  - name: Copy a file from local to remote
    copy:
        src: ./playbook_copy_file_to_cloud_vm.yml
        dest: /home/cc/
...

