---
- name: Install couchdb
  hosts: MyPrimaryVM
  remote_user:  cc

  tasks:
  - name: "Install couchdb dependencies"
    apt:
      pkg:
      - curl
      - apt-transport-https
      - gnupg
    become: yes
  
  - name: Add couchdb signing key
    ansible.builtin.apt_key:
      id: 390EF70BB1EA12B2773962950EE62FB37A00258D
      url: https://couchdb.apache.org/repo/keys.asc
      keyring: /usr/share/keyrings/couchdb-archive-keyring.gpg
    become: yes
  
  - name: Add repository to sources list
    ansible.builtin.apt_repository:
      repo: deb [signed-by=/usr/share/keyrings/couchdb-archive-keyring.gpg] https://apache.jfrog.io/artifactory/couchdb-deb/ focal main
      state: present
    become: yes

  - name: Install couchdb
    apt:
      pkg:
      - couchdb
    become: yes
...