---
- name: "Play 1: Provision Chameleon VMs"
  hosts: MyLocalVMs
  remote_user: cc
<<<<<<< HEAD
  gather_facts: no
  
=======

>>>>>>> 5ab8f8d (feat: add ability for couchdb to be connected to, and create meetup database)
  tasks:
  - include_tasks: ./playbook_create_chameleon_instances.yml

- name: "Play 2: Install packages and copy files"
  hosts: MyChameleonVMs
  remote_user: cc
  collections:
    - openstack.cloud
<<<<<<< HEAD
  gather_facts: no
  
=======

>>>>>>> 5ab8f8d (feat: add ability for couchdb to be connected to, and create meetup database)
  tasks:
  - include_tasks: ./playbook_install_packages.yml
  - include_tasks: ./playbook_copy_files.yml

- name: "Play 3: Set ufw"
  hosts: MyChameleonVMs
  remote_user: cc
  collections:
    - community.general
  gather_facts: no
  
  tasks:
  - include_tasks: ./playbook_set_ufw.yml

- name: "Play 4: Set up kafka"
  hosts: MyChameleonVMs
  remote_user: cc
  gather_facts: no
  
  tasks:
  - include_tasks: ./playbook_set_up_kafka.yml

- name: "Play 5: Set up primary VM"
  hosts: MyPrimaryVM
  remote_user: cc
  gather_facts: no
  
  tasks:
  - include_tasks: ./playbook_kafka_zookeeper_primary.yml
  - include_tasks: ./playbook_run_consumer.yml

- name: "Play 5: Set up secondary VM"
  hosts: MySecondaryVM
  remote_user: cc
  gather_facts: no
  
  tasks:
  - include_tasks: ./playbook_kafka_secondary.yml
...
