---
- hosts: MyChameleonVMs
  remote_user: cc
  collections:
    - openstack.cloud

  tasks:
  - name: Remove subversion (that we installed using the other playbook)
    apt: name=subversion state=absent purge=yes
    become: yes
...

