---
- hosts: MyChameleonVMs
  remote_user: cc
  collections:
    - openstack.cloud

  tasks:
  - name: Execute a command on remote cloud VM
    command: top -n 1 -b
    register: output

  - name: Print the output
    debug:
      msg: "{{ output }}"
...

